export enum ResponseStatus {
    STATUS_OK = 200,
    BAD_REQUEST = 400,
    INVALID_REQUEST = 422,
    UNAUTHENTICATED = 401,
    REQUEST_NOT_FOUND = 404,
    INTERNAL_SERVER_ERROR = 500,
    SERVICE_UNAVAILABLE = 503,
}
